"""Add engineering impact scoring columns

Revision ID: 98ac01c5eb78
Revises: b13c11b1de4c
Create Date: 2026-03-03 19:59:55.105421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98ac01c5eb78'
down_revision: Union[str, Sequence[str], None] = 'b13c11b1de4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('technical_depth_score', sa.Float(), nullable=True))
    op.add_column('problems', sa.Column('industry_impact_score', sa.Float(), nullable=True))
    op.add_column('problems', sa.Column('cognitive_complexity_score', sa.Float(), nullable=True))
    op.add_column('problems', sa.Column('signal_quality_score', sa.Float(), nullable=True))
    op.add_column('problems', sa.Column('engineering_impact_score', sa.Float(), nullable=True))
    op.add_column('problems', sa.Column('scoring_version', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_problems_engineering_impact_score'), 'problems', ['engineering_impact_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_problems_engineering_impact_score'), table_name='problems')
    op.drop_column('problems', 'scoring_version')
    op.drop_column('problems', 'engineering_impact_score')
    op.drop_column('problems', 'signal_quality_score')
    op.drop_column('problems', 'cognitive_complexity_score')
    op.drop_column('problems', 'industry_impact_score')
    op.drop_column('problems', 'technical_depth_score')
    # ### end Alembic commands ###
