"""Add Squad Collaboration features

Revision ID: f6898f165033
Revises: 98ac01c5eb78
Create Date: 2026-03-14 17:38:02.536916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6898f165033'
down_revision: Union[str, Sequence[str], None] = '98ac01c5eb78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collaboration_groups', sa.Column('leader_id', sa.Integer(), nullable=False))
    op.add_column('collaboration_groups', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('collaboration_groups', sa.Column('description', sa.Text(), nullable=True))
    op.drop_constraint(op.f('collaboration_groups_problem_id_key'), 'collaboration_groups', type_='unique')
    op.create_foreign_key(None, 'collaboration_groups', 'users', ['leader_id'], ['id'])
    op.add_column('collaboration_requests', sa.Column('group_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('unique_user_problem_request'), 'collaboration_requests', type_='unique')
    op.create_foreign_key(None, 'collaboration_requests', 'collaboration_groups', ['group_id'], ['id'])
    op.drop_index(op.f('problems_embedding_idx'), table_name='problems', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('problems_search_idx'), table_name='problems', postgresql_using='gin')
    op.alter_column('users', 'skills',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('users', 'interests',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'interests',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('users', 'skills',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.create_index(op.f('problems_search_idx'), 'problems', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('problems_embedding_idx'), 'problems', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_constraint(None, 'collaboration_requests', type_='foreignkey')
    op.create_unique_constraint(op.f('unique_user_problem_request'), 'collaboration_requests', ['user_id', 'problem_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('collaboration_requests', 'group_id')
    op.drop_constraint(None, 'collaboration_groups', type_='foreignkey')
    op.create_unique_constraint(op.f('collaboration_groups_problem_id_key'), 'collaboration_groups', ['problem_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('collaboration_groups', 'description')
    op.drop_column('collaboration_groups', 'name')
    op.drop_column('collaboration_groups', 'leader_id')
    # ### end Alembic commands ###
