"""Add Phase 4 fields: source_id, humanized_explanation, solution_possibility

Revision ID: 29f5c06cdf21
Revises: 5a63c0e90964
Create Date: 2025-12-30 10:48:34.169833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29f5c06cdf21'
down_revision: Union[str, Sequence[str], None] = '5a63c0e90964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('source_id', sa.String(length=255), nullable=True))
    op.add_column('problems', sa.Column('humanized_explanation', sa.Text(), nullable=True))
    op.add_column('problems', sa.Column('solution_possibility', sa.String(length=50), nullable=True))
    op.create_index('idx_source_source_id', 'problems', ['source', 'source_id'], unique=False)
    op.create_index(op.f('ix_problems_source_id'), 'problems', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_problems_source_id'), table_name='problems')
    op.drop_index('idx_source_source_id', table_name='problems')
    op.drop_column('problems', 'solution_possibility')
    op.drop_column('problems', 'humanized_explanation')
    op.drop_column('problems', 'source_id')
    # ### end Alembic commands ###
