"""Initial migration: all SolveStack models

Revision ID: 5a63c0e90964
Revises: 
Create Date: 2025-12-21 16:20:36.781058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a63c0e90964'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # FIXED: Removed invalid drop_table('problem_statements') - table doesn't exist
    op.alter_column('collaboration_groups', 'firebase_room_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_unique_constraint(None, 'collaboration_groups', ['problem_id'])
    op.alter_column('problems', 'difficulty',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text('("Intermediate")'))
    op.alter_column('problems', 'estimated_effort',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text('("1-3 days")'))
    op.alter_column('problems', 'score_updated_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('users', 'skills',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text('("[]")'))
    op.alter_column('users', 'experience_level',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text('("Intermediate")'))
    op.alter_column('users', 'interests',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text('("[]")'))
    op.alter_column('users', 'preferred_difficulty',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text('("Intermediate")'))
    op.alter_column('users', 'preferred_effort',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text('("1-3 days")'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'preferred_effort',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('("1-3 days")'))
    op.alter_column('users', 'preferred_difficulty',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('("Intermediate")'))
    op.alter_column('users', 'interests',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('("[]")'))
    op.alter_column('users', 'experience_level',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('("Intermediate")'))
    op.alter_column('users', 'skills',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('("[]")'))
    op.alter_column('problems', 'score_updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('problems', 'estimated_effort',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('("1-3 days")'))
    op.alter_column('problems', 'difficulty',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('("Intermediate")'))
    op.drop_constraint(None, 'collaboration_groups', type_='unique')
    op.alter_column('collaboration_groups', 'firebase_room_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # FIXED: Removed create_table('problem_statements') - not needed
    # ### end Alembic commands ###

